// Repository-specific inputs to the release scripts. The other scripts/*.mjs
// are verbatim copies of scshafe-dev's master (release/scripts/); change this
// file, not them. Generated by scshafe-dev v0.1.0. (ci.yml and publish.yml
// keep one known local difference, the Postgres service: CI15, PB27.)
export default {
  // Each directory in package.json `files` and what it may contain: the
  // TypeScript source, the built lib/, and the numbered migrations in sql/
  // (sql/NNN_name.sql only; the payload is what migrations ship).
  payload: { src: "\\.ts$", lib: "\\.(?:js|d\\.ts)$", sql: "^sql/\\d{3}_[a-z0-9_]+\\.sql$" },
  // Build output `pnpm run clean` removes; never committed (LIB-03).
  clean: ["lib"],
  // Packages the smokes need beside the peers (exact devDependencies).
  smokeExtraPackages: [],
  // Optional-peer phases, e.g. [{ name: "editor", peers: ["@tiptap/core"] }]:
  // the base smokes prove these peers are absent, then each phase adds its
  // peers and runs test/smoke/<name>/. The one peer, @scshafe/switchyard, is
  // required: the base phase installs it at its exact devDependency.
  phases: [],
  // false: the TypeScript smoke also checks the peers' declarations.
  typeSmokeSkipLibCheck: false,
  // DOM as well: peers' declarations name AbortSignal and friends (the
  // switchyard-postgres and graphpaper smokes check them the same way).
  typeSmokeLib: ["ES2022", "DOM"]
};
